# ----------------------------------------------------------------------------
# Copyright (c) 2023, QIIME 2 development team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------

import os
import q2templates

def aggregate_fastp_reports(report_dir: str, output_dir: str) -> None:
    """
    Combine individual HTML reports generated by fastp into a single HTML report.

    Args:
        report_dir (str): Directory containing individual HTML reports.
        output_dir (str): Directory to save the aggregated HTML report.

    Returns:
        None
    """
    reports = []
    for report_file in os.listdir(report_dir):
        if report_file.endswith('.html'):
            with open(os.path.join(report_dir, report_file), 'r') as f:
                reports.append(f.read())

    context = {'reports': reports}
    template = os.path.join(os.path.dirname(__file__), 'assets', 'fastp', 'index.html')
    q2templates.render([template], output_dir, context=context)

    # Generate the missing index.html file
    index_html_content = """
    <html>
    <head>
        <title>Aggregated fastp Reports</title>
    </head>
    <body>
        <h1>Aggregated fastp Reports</h1>
        {% for report in reports %}
            <div>{{ report|safe }}</div>
        {% endfor %}
    </body>
    </html>
    """
    with open(os.path.join(output_dir, 'index.html'), 'w') as f:
        f.write(index_html_content)
